when:
  - event: push
    branch: main

steps:
  - name: deploy-start-page
    image: alpine:3.20
    environment:
      DEPLOY_HOST: "10.0.0.13"   # your TrueNAS LAN IP
      DEPLOY_USER: "deploy"
      DEPLOY_PATH: "/mnt/NAS/apps/caddy/start-page"
    secrets:
      - DEPLOY_KEY
    commands:
      - apk add --no-cache openssh-client git

      # SSH key setup
      - mkdir -p /root/.ssh
      - echo "$DEPLOY_KEY" > /root/.ssh/id_ed25519
      - chmod 600 /root/.ssh/id_ed25519

      # SSH config
      - echo "Host *" > /root/.ssh/config
      - echo "  IdentityFile /root/.ssh/id_ed25519" >> /root/.ssh/config
      - echo "  StrictHostKeyChecking no" >> /root/.ssh/config

      # Trigger live update
      - ssh "$DEPLOY_USER@$DEPLOY_HOST" "cd '$DEPLOY_PATH' && git pull --ff-only"
