when:
  - event: [push, manual]
    branch: main

steps:
  - name: deploy-start-page
    image: alpine:3.20
    environment:
      DEPLOY_HOST: "10.0.0.13"
      DEPLOY_USER: "deploy"
      DEPLOY_PATH: "/mnt/NAS/apps/caddy/start-page"
      DEPLOY_KEY:
        from_secret: DEPLOY_KEY

    commands:
      - apk add --no-cache openssh-client git

      - mkdir -p /root/.ssh
      - echo "$DEPLOY_KEY" > /root/.ssh/id_ed25519
      - chmod 600 /root/.ssh/id_ed25519

      - echo "Host *" > /root/.ssh/config
      - echo "  IdentityFile /root/.ssh/id_ed25519" >> /root/.ssh/config
      - echo "  StrictHostKeyChecking no" >> /root/.ssh/config

      - ssh "$DEPLOY_USER@$DEPLOY_HOST" "cd '$DEPLOY_PATH' && git fetch origin main && git reset --hard origin/main && git clean -fd && VERSION=\$(git rev-parse --short HEAD) && sed -i \"s/style.css?v=__CACHE_BUST__/style.css?v=\$VERSION/\" index.html"